[package]
name = "sais_drum"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"
num-traits = "0.2.19"

[dev-dependencies]
proptest = "1.6.0"
lipsum = "0.9"
rand = "0.8.5"

# make things that are used in proptesting faster
[profile.test.package.proptest]
opt-level = 3
[profile.test.package.rand_chacha]
opt-level = 3
[profile.test.package.rand]
opt-level = 3
[profile.test.package.lipsum]
opt-level = 3
