name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -Dwarnings
    - name: Documentation
      run: cargo doc --no-deps --workspace
    - name: Format
      run: cargo fmt --all -- --check
